### PR TITLE
Add Pod Stats.

### PR DESCRIPTION
**Pull request by gauravgulati15**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

This PR resolves issue #4.

### CODE REVIEW

**Comment by gauravgulati15** [comment]
closes #4

**Comment by akshitadixit** [comment]
* Remove me
* Add a horizontal line before footer

**Comment by gauravgulati15** [comment]
@akshitadixit Fixed the minor issues. Kindly review it.
Thanks!

**Review by akshitadixit — APPROVED** [review]
Great work on the PR!

**Pull request merged**
