### PR TITLE
Project page

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
## Please, go through these steps before you submit a PR.
This PR resolves issue #6 and adds the following changes:
1. Placeholder images for project preview (since we don't have images of our completed projects as of now)
2. Adds more details to the project card with a flip animation
3. Fixes the layout of the project cards and also makes them responsive for mobile screens
4. Improves the project page style and adds a back button for easier navigation (kudos to @aku1310 for adding this!)

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by akshitadixit** [comment]
image
When flipping the card, the UI could be touched up a bit ig?

**Comment by Devansu-Yadav** [comment]
> image
> When flipping the card, the UI could be touched up a bit ig?

That's not how it looks like when I open the Netlify preview link on my device 🤔

**Comment by aku1310** [comment]
> When flipping the card, the UI could be touched up a bit ig?

It looks fine on my end as well 😅 (attaching mobile version screenshot)
image

**Comment by akshitadixit** [comment]
Let's go ahead with your verdict then assuming my browser and its adblocker have gone berserk :')

**Review by akshitadixit — APPROVED** [review]

**Pull request merged**
