### PR TITLE
Add pod fellows

### PR DESCRIPTION
**Pull request by SudhanshuBlaze**
**Enhancement** – Issue #13  

1.  Add all the fellows' name, location, profile picture, social links and resumes in `_data/fellows.yml`.
2.  Implemented the anchor tag in the ` _includes/descriptions.html`.
3. Updated `config.yml` with our pod title.
4. Fixed minor typos in the `Readme.md`.

- [X] My Pod Leader knows I'm working on this Pull Request
- [X] I've explained what the Pull Request is adding.
- [X] I've explained why this is important.

### CODE REVIEW

**Comment by akshitadixit** [comment]
@SudhanshuBlaze @rk119 is this expected in the deploy preview?
image

**Comment by rk119** [comment]
> @SudhanshuBlaze @rk119 is this expected in the deploy preview? image

Yes, because the profile picture layout is an issue handled by another team. We were responsible to include only the fellow details as stated in our issue.

**Comment by akshitadixit** [comment]
Please fix the conflict and we should be good to go.

**Comment by rk119** [comment]
> Please fix the conflict and we should be good to go.

Unfortunately, since we raised our pull request before the other pull request got merged, it is asking to discard 30 commits to sync.

**Comment by SudhanshuBlaze** [comment]
Hiii @akshitadixit we fixed the merge conflicts, please review it.

**Pull request merged**
