### PR TITLE
add footer

### LINKED ISSUE #1: Add a footer
Add a footer that acts a site map, and includes some information about the pod, such as:

- Blog
- About
- Socials
- Projects

### PR DESCRIPTION
**Pull request by irsayvid**
Adds footer for the website with sitemap links, social links and about. This is important because the footer is reusable through various pages and can be used to overview various pages on the website and highlight social links.
Fixes #1 
- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by irsayvid** [comment]
CC: @amv2

**Comment by irsayvid** [comment]
@akshitadixit please review the PR and let us know if any changes are needed

**Review by akshitadixit — CHANGES_REQUESTED** [review]
1. Reduce the logo size just a bit 🤏 
2. Undo the auto-formatter changes

**Comment by akshitadixit** [comment]
It is good practice to use present tense in commit messages. Words like `changed`, `removed` should be replaced with `change` and `remove` for next time :)

**Comment by akshitadixit** [comment]
LGTM 🚀

**Pull request merged**
